### ISSUE TITLE
Not working fab outside bottom bar example

### ISSUE THREAD

**Issue by Frezyx** [Frezyx/bottom_bar_with_sheet#30]
Due to the new functionality from this https://github.com/Frezyx/bottom_bar_with_sheet/pull/29 pr associated with auto-close.

**Comment by fhidal01** [comment]
I want to verify that what I am experiencing is the same as this issue here before creating a new issue.

I am using the  isOpened attribute to try and programmatically open and close the sheet by changing its value in my widget with setState but its not doing anything the the sheet. I don't have a way to programmatically open and close it.

Is what I described a new issue or is it a know issue introduced in this #29 pr??

**Comment by fhidal01** [comment]
Is there any work being done to fix this?

**Comment by Frezyx** [comment]
Now package api is updated
All the necessary functionality is now in the controller
